export const tutorialsPageCopy = {
  metadata: {
    title: 'Tutorials',
    description: 'Short visual guides for setting up Kira, finding manga, reading offline, and personalizing the app.',
  },
  hero: {
    eyebrow: { en: 'KIRA HELP CENTER', ar: 'مركز مساعدة كيرا' },
    title: {
      lead: { en: 'Learn Kira,', ar: 'تعلّم كيرا،' },
      accent: { en: 'one chapter at a time.', ar: 'فصلًا بعد فصل.' },
    },
    description: {
      en: 'Short, visual answers for everything from first setup to offline reading.',
      ar: 'إجابات قصيرة وبصرية لكل شيء، من الإعداد الأول إلى القراءة دون إنترنت.',
    },
    browseCta: { en: 'Browse tutorials', ar: 'تصفّح الشروحات' },
    supportCta: { en: 'Get support', ar: 'احصل على دعم' },
    proof: [
      { en: 'Visual walkthroughs', ar: 'شروحات مرئية' },
      { en: 'Arabic and English', ar: 'العربية والإنجليزية' },
      { en: 'Practical steps only', ar: 'خطوات عملية فقط' },
    ],
  },
  library: {
    allCategory: { en: 'All guides', ar: 'كل الشروحات' },
    sectionLabel: { en: 'GUIDE LIBRARY', ar: 'مكتبة الشروحات' },
    title: { en: 'Find the answer, then keep reading.', ar: 'اعثر على الإجابة ثم أكمل القراءة.' },
    searchLabel: { en: 'Search tutorials', ar: 'ابحث في الشروحات' },
    searchPlaceholder: { en: 'Search tutorials…', ar: 'ابحث في الشروحات…' },
    categoriesLabel: { en: 'Tutorial categories', ar: 'تصنيفات الشروحات' },
    count: {
      en: { one: 'guide', many: 'guides' },
      ar: { one: 'شرح', many: 'شروحات' },
    },
    steps: { en: 'steps', ar: 'خطوات' },
    openGuide: { en: 'Open guide', ar: 'افتح الشرح' },
    emptyTitle: { en: 'No guide matches that search.', ar: 'لا يوجد شرح يطابق هذا البحث.' },
    emptyDescription: { en: 'Try a shorter phrase or choose All guides.', ar: 'جرّب عبارة أقصر أو اختر «كل الشروحات».' },
    clearFilters: { en: 'Clear filters', ar: 'امسح الفلاتر' },
    unavailableTitle: { en: 'Tutorials are temporarily unavailable.', ar: 'الشروحات غير متاحة مؤقتًا.' },
    unavailableDescription: { en: 'The rest of Kira is still available. Please try the guide library again shortly.', ar: 'بقية موقع كيرا ما زالت متاحة. أعد محاولة فتح مكتبة الشروحات بعد قليل.' },
  },
  article: {
    tutorialLibraryLabel: 'Tutorial library',
    allTutorials: { en: 'All tutorials', ar: 'كل الشروحات' },
    quickGuides: { en: 'QUICK GUIDES', ar: 'أدلة سريعة' },
    stillNeedHelp: { en: 'Still need help?', ar: 'ما زلت تحتاج مساعدة؟' },
    openSupport: { en: 'Open support', ar: 'افتح الدعم' },
    breadcrumbLabel: 'Breadcrumb',
    tutorials: { en: 'Tutorials', ar: 'الشروحات' },
    mediaTitle: 'KIRA / GUIDE MEDIA',
    mediaStatus: 'GUIDE VIEW',
    mediaCaption: { en: 'Kira screen reference for this step', ar: 'مرجع من شاشة كيرا لهذه الخطوة' },
    inThisGuide: { en: 'IN THIS GUIDE', ar: 'في هذا الشرح' },
    stepPrefix: { en: 'STEP', ar: 'الخطوة' },
    tipLabel: { en: 'Good to know', ar: 'معلومة مفيدة' },
    continueLearning: { en: 'CONTINUE LEARNING', ar: 'أكمل التعلّم' },
    onThisPageLabel: 'On this page',
    readSuffix: { en: 'read', ar: 'قراءة' },
    unavailableTitle: { en: 'This tutorial is temporarily unavailable.', ar: 'هذا الشرح غير متاح مؤقتًا.' },
    unavailableDescription: { en: 'Please try again shortly. No website rebuild is required when the service recovers.', ar: 'أعد المحاولة بعد قليل. سيعود الشرح تلقائيًا عند استعادة الخدمة.' },
  },
} as const;
